function choice = gui_pop(text)
% Help goes here.
S.fh = figure('units','pixels',...
              'position',[300 300 100 250],...
              'menubar','none',...
              'name','gui_pop',...
              'numbertitle','off',...
              'resize','off');
          
S.pbr = uicontrol('style','push',...
                 'unit','pix',...
                 'position',[40 170 40 40],...
                 'fontsize',12,...
                 'fontweight','bold',... 
                 'string','',...
                 'callback',@pb_robot);
             
             
S.pbc = uicontrol('style','push',...
                 'unit','pix',...
                 'position',[40 110 40 40],...
                 'fontsize',12,...
                 'fontweight','bold',...
                 'string','',...
                 'callback',@pb_cisim);
    
S.pbg = uicontrol('style','push',...
                 'unit','pix',...
                 'position',[40 48 40 40],...
                 'fontsize',12,...
                 'fontweight','bold',...
                 'string','',...
                 'callback',@pb_hedef);

S.tf4 = uicontrol('Style','text',...
                'String',text,...
                'Position',[20 215 80 35],...
                'FontSize' , 10);             
             
S.tf1 = uicontrol('Style','text',...
                'String','Robot',...
                'Position',[35 153 50 16]);
            
S.tf2 = uicontrol('Style','text',...
                'String','Cisim',...
                'Position',[35 90 50 16]);
            
S.tf3 = uicontrol('Style','text',...
                'String','Hedef',...
                'Position',[35 30 50 16]);
             
             % Butonlara Ýcon Ekleniyor
             X = imread('icons\robot.jpg');
             set(S.pbr,'CData',X);
             
                          % Butonlara Ýcon Ekleniyor
             X = imread('icons\cisim.jpg');
             set(S.pbc,'CData',X);
             
                          % Butonlara Ýcon Ekleniyor
             X = imread('icons\hedef.jpg');
             set(S.pbg,'CData',X);
         
             choice = 'Null';

guidata(S.fh,S)
movegui('center')
uiwait(S.fh);

    function pb_robot(varargin)
        choice = 'Robot';
        delete(S.fh);
    end
    function pb_cisim(varargin)
        choice = 'Cisim';
        delete(S.fh);
    end
    function pb_hedef(varargin)
        choice = 'Hedef';
        delete(S.fh);
    end
end


